name:  rpbs-jupyterhub-course
channels:
  - r
  - conda-forge
  - anaconda
dependencies:
  - python
  - gcc
  - gfortran_linux-64
  - r-essentials
  - notebook
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - bokeh
  - requests
  - scikit-learn
  - qgrid
  - vega
  - networkx
  - simplegeneric
  - rpy2
  - version_information
  - rise
  - ipyleaflet
  - tzlocal
  - geopandas
  - nglview
