name:  rpbs-jupyterhub-course
channels:
    - conda-forge
dependencies:
    - numpy=1.16
    - pyqt=5.9
    - ipython=7.5
    - notebook=5.7
    - jupyter=1.0
    - scipy=1.3
    - pandas
    - matplotlib
    - seaborn
    - plotly
    - bokeh
    - requests
    - scikit-learn
    - qgrid
    - vega
    - networkx
    - simplegeneric
    - rpy2
    - version_information
    - rise
    - ipyleaflet 
    - tzlocal
    - geopandas
    - nglview
    - xeus-cling
